### ISSUE TITLE
[QUESTION] Will the v1 api continue to be supported?

### ISSUE THREAD

**Issue by louisbuchbinder** [DopplerHQ/cli#135]
Hello, this is not an issue just a question.

It is clear that the legacy doppler cli's are EOL based on: https://doppler.com/changes/all-clients-are-end-of-life

I am curious if there are plans to EOL the v1 api as well? My fear is that since the "token" section of the website is listed under the "legacy" tab that this is the case.

My employer is currently using doppler as the source of truth for our secrets. Based on some _reasons_ those secrets were fetched from doppler in ci/cd and inserted directly into ecs task-definitions and lambda config envs. I am working on removing those values from the config and moving to a system where we fetch the values directly from doppler in the application runtime. It seems that the "doppler" way is to execute my program as a command line arg to the doppler cli, which will inject the secrets as environment variables. I am not particularly impressed with that design decision for a number of reasons like: unnecessary added complexity, uncertain usage with lambda, inability to modify secrets without an application deploy, ... etc. I would much prefer to fetch the secrets as needed and I was very happy to discover the v1 api. BUT before I go any further down that path I wanted to get some clarity on the doppler roadmap just in case there are any plans for removing the public api altogether.

Thank you for your response

**Comment by Piccirello** [comment]
Our v1 API is deprecated, and we do plan to EOL it at the end of the year. However, our APIs are certainly not going away. Our latest v3 API provides much of the same functionality ([docs](https://docs.doppler.com/reference#enclave-config-secret-list)). Additionally, while Legacy Tokens are not strictly recommended (CLI tokens and Service tokens are preferable), we currently do not have any plans to deprecate them. If they are eventually deprecated, it will be many months after we release a comparable solution.

It is worth noting that Doppler supports syncing your secrets directly to AWS Parameter Store and AWS Secret Manager. This would ensure your lambda functions always have the latest secrets while also ensuring you never exceed Doppler's rate limit. You can find more information on those integrations [here](https://docs.doppler.com/docs/aws-parameter-store) and [here](https://docs.doppler.com/docs/aws-secrets-manager).

**Comment by louisbuchbinder** [comment]
oh thank you. Syncing with PS is exactly what I am looking for
