### ISSUE TITLE
[FEATURE] Make doppler run play nicely with systemd

### ISSUE THREAD

**Issue by ryan-blunden** [DopplerHQ/cli#152]
**Is your feature request related to a problem? Please describe.**

See the [PHP on NGINX with Doppler and Systemd](https://gist.github.com/ryan-blunden/0d928bebab39f5ee6129b081386f86f0) guide for context.

When using doppler run to spawn the php-fpm process, it hangs and requires a SIGINT.

Upon getting the status of the Systemd php-fpm service, it outputs the following, where 12951 is the php-fpm process and 12931 is doppler.

```sh
Oct 27 01:54:26 ip-10-0-0-163 systemd[1]: Starting The PHP 7.4 FastCGI Process Manager...
Oct 27 01:54:26 ip-10-0-0-163 systemd[1]: php7.4-fpm.service: Got notification message from PID 12951, but reception only permitted for main PID 12931
Oct 27 01:54:36 ip-10-0-0-163 systemd[1]: php7.4-fpm.service: Got notification message from PID 12951, but reception only permitted for main PID 12931
```

This isn't a huge deal when manually configuring things, but is a blocker for automated solutions such as an Ansible playbook.

**Describe alternatives you've considered**
There might be another way to fix this but I'm not sure.

**Additional context**

**Comment by lux** [comment]
Here's an Ansible role I came up with to try automating the php-fpm steps:

[doppler-php-fpm.zip](https://github.com/DopplerHQ/cli/files/5459642/doppler-php-fpm.zip)

Not directly related to the hanging issue, but hope that helps in testing.

**Comment by ryan-blunden** [comment]
Thanks John (@lux). This will definitely come in handy.

**Comment by ryan-blunden** [comment]
Closing as we now have a [solution for populating environment variables for PHP-FPM](https://github.com/DopplerHQ/php-examples/blob/main/Makefile#L24)
