### ISSUE TITLE
[BUG] Unsupported architecture - Apple Silicon

### ISSUE THREAD

**Issue by andrespera** [DopplerHQ/cli#168]
**Describe the bug**
I am trying to run the Doppler CLI install script in a docker container from PHP:7.4-fpm-alpine, but whenever I get to that steps it fails.

**To Reproduce**
1. FROM PHP:7.4-fpm
2. RUN (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh
3. See ERROR: Unsupported architecture 'aarch64'

**Expected behavior**
I expect the script to install doppler in the container

**Screenshots**

<img width="896" alt="Screen Shot 2020-12-16 at 10 15 45 AM" src="https://user-images.githubusercontent.com/4164624/102367395-baad8180-3f87-11eb-9f4b-4cd5ff7b9306.png">

**Desktop (please complete the following information):**
 - OS: mac OSX - running M1
 - Version 11.1

**Comment by Piccirello** [comment]
Go does not yet support building for amd64 (Apple Silicon) on macOS, but we are tracking this internally. Support will be added for this in [Go 1.16](https://tip.golang.org/doc/go1.16#darwin), which should be released in February 2021. Once 1.16 is released, we will release a new build with support for Apple Silicon.

**Comment by aaronspindler** [comment]
Is there any update on this bug? I am encountering it today.

**Comment by Piccirello** [comment]
Apple silicon support was added in [Doppler CLI v3.23.0](https://github.com/DopplerHQ/cli/releases/tag/3.23.0).
