### ISSUE TITLE
[BUG] Unexpected 404 using CLI install script

### ISSUE THREAD

**Issue by chrisjacobs91** [DopplerHQ/cli#171]
**Describe the bug**

**To Reproduce**
1. Click on '....'
1. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version [e.g. 10.15.1]

**CLI Version:**
Version [e.g. 1.0.0]

**Additional context**

**Comment by Piccirello** [comment]
Could you add some more information to this issue? OS and architecture would be helpful (`uname -a`), as well as output from running the script with the `--debug` flag.
