### ISSUE TITLE
[BUG] Unsupported architecture

### ISSUE THREAD

**Issue by wolterlw** [DopplerHQ/cli#189]
Doppler cli is not available on mips architecture (exact device [Onion Omega2Pro](https://onion.io/store/omega2-pro/), operating system OpenWRT)

**Comment by Piccirello** [comment]
That looks like a pretty cool device! Could you post the result of running `uname -sm` on it? This will give us a better sense of exactly what OS and architecture we would need to support.

**Comment by wolterlw** [comment]
It is quite nifty
```
~# uname -sm
Linux mips
```
not too verbose though

**Comment by Piccirello** [comment]
I've generated a test build for linux/mips. Could you extract it and run `./doppler --version` to verify this binary executes for you?

[doppler-mips.zip](https://github.com/DopplerHQ/cli/files/6137537/doppler-mips.zip)

**Comment by wolterlw** [comment]
```
~/tools# ./doppler --version
./doppler: line 1: syntax error: unexpected "("
```

**Comment by Piccirello** [comment]
Hmm, that's odd. That binary was compiled using `GOOS=linux GOARCH=mips make build`. Go 1.16 seems to support 4 different mips architectures for Linux:

```sh
$ go version
go version go1.16 darwin/amd64
$ go tool dist list | grep mips
linux/mips
linux/mips64
linux/mips64le
linux/mipsle
openbsd/mips64
```

I've included a build for each of the four supported architectures. Could you see if any of them work for you?

[doppler-mips64.zip](https://github.com/DopplerHQ/cli/files/6143563/doppler-mips64.zip)
[doppler-mips64le.zip](https://github.com/DopplerHQ/cli/files/6143564/doppler-mips64le.zip)
[doppler-mipsle.zip](https://github.com/DopplerHQ/cli/files/6143565/doppler-mipsle.zip)
[doppler-mips.zip](https://github.com/DopplerHQ/cli/files/6143562/doppler-mips.zip)

**Comment by wolterlw** [comment]
I have tested all 4 versions and `doppler-mipsle` is the only one properly displaying the version.

**Comment by Piccirello** [comment]
This is tricky given that the architecture the OS identifies as is different than the architecture it seems to want applications to be compiled for. I'm hesitant to add support to our install scripts for using the mipsle binary when the OS self-identifies as mips. I'm not sure that this edge-case will be sufficiently generic.

**Comment by Piccirello** [comment]
Closing this issue as I'm not sure there's a clear path forward. Please re-comment if you'd like to continue troubleshooting this.
