### ISSUE TITLE
[FEATURE] Helm CRD operator for ease k8s installation

### ISSUE THREAD

**Issue by saikatharryc** [DopplerHQ/cli#206]
Is there any CRD available already which we can use just like vault operator?

**Comment by ryan-blunden** [comment]
HI @saikatharryc,

I'm working on an experimental CRD that I'll have ready for testing this week and I'll reply back once it's ready.

**Comment by ryan-blunden** [comment]
Hi @saikatharryc,

Sorry for the delay in responding but our (experimental) [Doppler CR controller](https://github.com/DopplerHQ/doppler-k8s-controller) is now ready for testing and I would love your feedback.

I have not yet added a Helm chart but have [created an issue](https://github.com/DopplerHQ/doppler-k8s-controller/issues/2) for this.
