### ISSUE TITLE
Doppler 3.23.3 on Windows 10 AMD is incorrect build type

### ISSUE THREAD

**Issue by ryan-blunden** [DopplerHQ/cli#213]
When installing the 3.23.4 via Scoop on Windows, [the doppler.exe executable is unable to run](https://community.doppler.com/t/doppler-dont-work-on-windows/208)

I've been able to reproduce this on Windows 10 by using the Scoop commands in our docs.

As a test, I downloaded the AMD zip from the 3.23.3 release and replaced the `doppler.exe` in `C:\Users\rb\scoop\apps\doppler\current` folder which I was able to run without error.

**Comment by Piccirello** [comment]
Doppler CLI v3.24.4 has been published and this should now be resolved.
