### ISSUE TITLE
[FEATURE] Protip: Add `secret-management ` to your list of tags on the repo

### ISSUE THREAD

**Issue by smac89** [DopplerHQ/cli#250]
This just means you guys appear in this list: https://github.com/topics/secret-management. Good for SEO

Also Github has discussions built in. Please enable it so that non-issues like this can be posted there instead of here

**Comment by Piccirello** [comment]
Thanks for the recommendation- I've added that tag to the repo.

> Also Github has discussions built in. Please enable it so that non-issues like this can be posted there instead of here

I'll chat with the team about enabling this. We've traditionally relied on our [Community](https://community.doppler.com/) for these sorts of discussions (which uses Discourse).
