### ISSUE TITLE
[BUG] the info message printed with fallback should be sent to stderr, not stdout

### ISSUE THREAD

**Issue by smac89** [DopplerHQ/cli#271]
**Describe the bug**
I was trying to do
```
myvar="$(doppler run --fallback-only -- some command here)"
```
...expecting to just get the output of `some command here`, however the output `Reading secrets from fallback file` is also part of the value of `myvar`

**To Reproduce**

**Expected behavior**
Only after experiencing this error did I discover the `--silent` flag which works to eliminate this message. I think it's pretty standard for such messages to go directly to stderr instead of stdout. What do you think?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: alpine
 - Version latest

**CLI Version:**
Version 3.34.1

**Additional context**

**Comment by Piccirello** [comment]
Thanks for reporting this. The CLI currently doesn't follow best practices around what to send to stdout vs stderr. I'll see if I can get a fix up for this this week.
