### ISSUE TITLE
[BUG] Env variables not populated if running as sudo.

### ISSUE THREAD

**Issue by RemiKalbe** [DopplerHQ/cli#287]
**Describe the bug**
If I run a program as sudo, the env variables that should be populated by doppler, aren't.

**To Reproduce**
A simple javascript file
```js
console.log("ENV: " + process.env.MY_AMAZING_VAR);
```
If I run
```bash
doppler run -- node test.js
```
I get back
```
ENV: My amazing var's value
```

But if I run as root
```bash
doppler run -- sudo node test.js
```
I get
```
ENV: undefined
```

**Expected behavior**
To have my ENV var populated, whether or not I use sudo.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.0.1 (21A559)

**CLI Version:**
Version 3.36.0

**Comment by RemiKalbe** [comment]
If I run it like so
```bash
sudo doppler run -- node test.js
```
It works, but I'll keep this issue open in case it should also works as I described.

**Comment by Piccirello** [comment]
This is a feature of the `sudo` command. You must pass the `--preserve-env` flag (or `-E`) to retain these variables in your new shell.

https://man7.org/linux/man-pages/man8/sudo.8.html
