### ISSUE TITLE
Install on Windows with Bash

### ISSUE THREAD

**Issue by mweber-ak** [DopplerHQ/cli#302]
None of our engineers use scoop or powershell. Every engineer I know uses git bash for windows

**Describe the solution you'd like**
Instructions for installing the CLI on Windows using bash.

**Describe alternatives you've considered**
A normal program installer like most tools on windows.

**Comment by mweber-ak** [comment]
For context, we have 140 engineers, we'd like to use doppler, we can't if people cannot install the cli simply and easily.

**Comment by mweber-ak** [comment]
I'm also getting reports from Mac users about difficulties, will ask them to make a separate issue.

**Comment by watsonian** [comment]
@mweber-ak We just merged in a change that should make it pretty easy to install the Doppler CLI in Git Bash. Take a look [here](https://github.com/DopplerHQ/cli/blob/master/INSTALL.md#git-bash). Let us know if you have any trouble with it!
