### ISSUE TITLE
Distribute CLI via winget for Windows

### ISSUE THREAD

**Issue by tallpants** [DopplerHQ/cli#311]
winget is the first party package manager from Microsoft that's included by default in Windows 11 and newer versions of Windows 10: https://docs.microsoft.com/en-us/windows/package-manager/winget/

Instructions for distributing a package through winget are also fairly straightforward and low effort: https://docs.microsoft.com/en-us/windows/package-manager/package/

Doing this would remove the need for Windows users to install Scoop first before they can install Doppler and would bring the Windows installation instructions down to essentially "please run `winget install DopplerHQ.doppler-cli`" or similar.

**Comment by Piccirello** [comment]
This is a cool idea and something we're tracking internally, but no ETA to share as of yet. We're current blocked on the tooling we use ([goreleaser](https://github.com/goreleaser/goreleaser/issues/2290)) adding support for it.

**Comment by Hawxy** [comment]
@Piccirello Would it be possible to publish to Chocolatey in the interim? A lot of devs have it installed already due to node.js.

**Comment by Piccirello** [comment]
Unfortunately it appears that goreleaser doesn't yet support Chocolatey, for the same reasons that it isn't yet able to support winget. Once support is added, we'll likely only publish to winget.

**Comment by ryan-blunden** [comment]
Looks like progress is being made with winget now supporting the installation of stand-alone apps.

https://github.com/goreleaser/goreleaser/issues/1295#issuecomment-1153285862

**Comment by Hawxy** [comment]
winget support is still stalled for some reason, although Choco is now supported: https://goreleaser.com/customization/chocolatey/

**Comment by Piccirello** [comment]
Closed in #409. The CLI is now available via `winget install doppler`. Some more work is needed to get updates working from within the CLI, but in the interim you can upgrade via `winget upgrade doppler`.
