### ISSUE TITLE
The changes work well for me :+1:

### ISSUE THREAD

**Issue by Giangpro89** [DopplerHQ/cli#315]
The changes work well for me :+1: 

I confirmed that all three preference values work well, with different nested structures. Git operations on the nodes also work well and are properly handled by all three preference values.

_Originally posted by @vince-fugnitto in https://github.com/eclipse-theia/theia/pull/11256#pullrequestreview-1006003295_

**Comment by vince-fugnitto** [comment]
@ryan-blunden @Giangpro89 what is this?

**Comment by ryan-blunden** [comment]
@vince-fugnitto I wasn't sure either which is why I've closed this issue.
