### ISSUE TITLE
[BUG] syntax error in /etc/bash_completion.d/doppler

### ISSUE THREAD

**Issue by jheyer159** [DopplerHQ/cli#369]
**Describe the bug**
After installing doppler using ```(curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sudo sh```

I'm getting the following error

```
source ~/.bash_profile
sh: /etc/bash_completion.d/doppler: line 129: syntax error near unexpected token `<'
sh: /etc/bash_completion.d/doppler: line 129: `        done < <(compgen -W "${out}" -- "$cur")'
```

**To Reproduce**
1. Install doppler cli
2. `source ~/.bash_profile`
3. See error

**Expected behavior**
No syntax error

**Desktop (please complete the following information):**
```NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**CLI Version:**
v3.54.0

**Comment by Piccirello** [comment]
I'm not able to reproduce this. Are you still experiencing this issue?

**Comment by jheyer159** [comment]
I've stopped using this OS and haven't run into this in other environments.
