### ISSUE TITLE
[BUG] Unexpected 404 using CLI install script

### ISSUE THREAD

**Issue by sjl2** [DopplerHQ/cli#372]
**Describe the bug**
We're attempting to download the CLI to use within CI.

**To Reproduce**
```
#!/bin/bash -eo pipefail
(curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh -s -- --no-install --no-package-manager
```

**Expected behavior**
It installs successfully. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8300986/221734287-a38caa65-4536-42aa-813f-100ec2e1bc9a.png)

**Desktop (please complete the following information):**
- Docker Image:  `cimg/ruby:2.7.6-browsers`

**CLI Version:**
Latest

**Additional context**
This is occurring on many of our CircleCI jobs, preventing us from merging in critical changes.

**Comment by Piccirello** [comment]
This appears to have been caused by an intermittent GitHub caching issue and should now be resolved.
