### ISSUE TITLE
[BUG] Doppler CLI fails to install on debian, started today 3/22

### ISSUE THREAD

**Issue by willywu** [DopplerHQ/cli#375]
**Describe the bug**
Installing doppler CLI on debian is failing, starting new as today 3/22

**To Reproduce**
Steps to reproduce the behavior. Please include output from running the command with `--debug`.
1. Follow instructions in https://docs.doppler.com/docs/install-cli to install the CLI for debian
2. Eventually, the "apt-get -y install doppler" command fails.  Here are logs from our CI system:
```
Step 9/12 : RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg &&     curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | apt-key add - &&     echo "deb https://packages.doppler.com/public/cli/deb/debian any-version main" | tee /etc/apt/sources.list.d/doppler-cli.list &&     apt-get update &&     apt-get -y install doppler
 ---> Running in 45aae5601cf5
....
Setting up apt-transport-https (2.2.4) ...
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
deb https://packages.doppler.com/public/cli/deb/debian any-version main
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Ign:4 https://packages.doppler.com/public/cli/deb/debian any-version InRelease
Err:5 https://packages.doppler.com/public/cli/deb/debian any-version Release
  404  Not Found [IP: 108.138.64.64 443]
Reading package lists...
E: The repository 'https://packages.doppler.com/public/cli/deb/debian any-version Release' does not have a Release file.
```

**Expected behavior**
Doppler CLI should install successfully

**Desktop (please complete the following information):**
 - OS: Debian
 - Version 11 (bullseye)

**Comment by nicoandmee** [comment]
We are also experiencing this issue. +1

**Comment by joeka36** [comment]
Also experiencing this on `debian:buster`. Tried pulling an `ubuntu` docker image and installing - looks like it is failing on Ubuntu as well

**Comment by willywu** [comment]
It looks like they're posting updates about this issue at https://www.dopplerstatus.com/incidents/h1k1xzfvvbbq

**Comment by willywu** [comment]
Closing this, it looks like their package host provider had an issue.
