### ISSUE TITLE
[FEATURE] Watch and auto-reload for `doppler run`

### ISSUE THREAD

**Issue by devunt** [DopplerHQ/cli#378]
**Is your feature request related to a problem? Please describe.**
It's annoying to stop and re-run `doppler run` after changes are made on Doppler dashboard.

**Describe the solution you'd like**
A `--watch` flag. It will periodically polling Doppler API for any changes and if changes found, it will restart the provided command.

**Describe alternatives you've considered**
Nothing viable.

**Additional context**
It would be very helpful in local development.

**Comment by Piccirello** [comment]
Closed via #408. This will be released to all Team workplaces within the next few days, and then made generally available over the next few weeks.
