### ISSUE TITLE
[BUG] Cannot CTRL-C ray serve when running with doppler

### ISSUE THREAD

**Issue by lukasschmit** [DopplerHQ/cli#382]
**Describe the bug**
I am trying to develop using [ray serve](https://docs.ray.io/en/latest/serve/index.html) locally. When I do

`doppler run -- serve run test:binding`

The process runs but cannot be killed with CTRL-C/D. I have to `kill -9` it.

**To Reproduce**

```
pip install "ray[serve]"
doppler run -- test:binding # attached
```
[test.py.zip](https://github.com/DopplerHQ/cli/files/11263718/test.py.zip)

**Expected behavior**
I expect the process to be able to be killed normally, but CTRL-C/D are unresponsive.

**Screenshots**
<img width="856" alt="Screenshot 2023-04-18 at 11 40 28 AM" src="https://user-images.githubusercontent.com/4791204/232829848-7597dc1d-63f9-445c-b2f2-612acdead14b.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1 (M2 MAX 16" MBP)
 - Version [e.g. 10.15.1]

**CLI Version:**
```
doppler --version
v3.56.2
```

**Comment by Piccirello** [comment]
Could you try this again with the `--forward-signals` flag? i.e. `doppler run --forward-signals -- serve run test:binding`
