### ISSUE TITLE
[FEATURE] Configure doppler repo-wide to stop asking to update itself

### ISSUE THREAD

**Issue by osdiab** [DopplerHQ/cli#422]
**Is your feature request related to a problem? Please describe.**
In my project we use [`asdf`](https://github.com/takutakahashi/asdf-doppler) to install specific versions of the tools we use, so that all of the members of our team are using the same version tools.

But `doppler` prompts individuals to install the latest version by default. There's a flag to prevent this, but then we have to make sure as a team to always provide that flag whenever we invoke the CLI, which is impractical beyond a couple people.

**Describe the solution you'd like**
A way to configure centrally in a repository that we don't want to check for updates, since we're managing the version separately.

**Describe alternatives you've considered**
Adding `--no-check-version` or the equivalent environment variable to every invocation of Doppler in my monorepo, but that's a game of whack-a-mole trying to make sure that in a large sprawling monorepo that we don't ever miss it.

**Comment by Piccirello** [comment]
Would running a command like `doppler update disable` be sufficient? It would persist the preference to the config file in your home directory.

**Comment by osdiab** [comment]
didn't know that existed, doesn't look like there's any docs for it - but i would want this to be scoped to the repo all of my teammates are working on, and applied automatically the moment they clone the repository. I'm guessing from your description of the command that this is not reflected in a config file directly in the repo?

**Comment by Piccirello** [comment]
I was trying to scope out a potential solution before building anything; it doesn't exist yet. I can understand why you would want this setting to be more easily configurable. What if this were a value you could specify in your doppler.yaml and that was set when running `doppler setup`? That's the only repo-specific configuration file that we currently support.

**Comment by osdiab** [comment]
That would make sense to me, if Doppler.yml in general allowed specifying default cli flags i find that useful (similar to how many other tools allow configuration via files).

**Comment by nmanoogian** [comment]
@osdiab, thanks again for reaching out about this! We've added "flags" to the latest version of the CLI which allows users to run `doppler configure flags disable update-check` to set a preference that disables the automatic version check behavior from the Doppler CLI.

This flag can also be set in the `doppler.yaml` file so that your team's preferences will automatically be set when team members run `doppler setup`:

```yaml
setup:
  - project: backend
    config: dev
flags:
  update-check: false
```

We'd love to hear how these new features work out for your team!

**Comment by osdiab** [comment]
I set it up and it looks good! Thanks!

Omar

**Comment by nmanoogian** [comment]
Amazing, thanks!
