### ISSUE TITLE
[BUG] `doppler tui` loads no data and crashes on Tab press

### ISSUE THREAD

**Issue by blakemorgan** [DopplerHQ/cli#424]
**Describe the bug**
When I execute `doppler run` with no CLI param, the TUI loads with no data. Then when I press Tab, it crashes and I see the error `Doppler Exception: runtime error: invalid memory address or nil pointer dereference`

**To Reproduce**
Steps to reproduce the behavior. Please include output from running the command with `--debug`.
1. `doppler tui --debug`. TUI loads with no data
1. Press "Tab" key
1. See error:

```
Debug: Using config dir /Users/bmorgan/.doppler
Debug: Using config file /Users/bmorgan/.doppler/.doppler.yaml
Debug: Reading config file
Debug: Retrieving token from system keyring
Debug: Sending anonymous analytics payload: '{"command":"doppler.tui"}'
Debug: Performing HTTP POST to https://cli.doppler.com/v1/analytics
Doppler Exception: runtime error: invalid memory address or nil pointer dereference
```

**Expected behavior**
The TUI should load with all Configs and Projects I have access to. Then when I press the Tab key, it should not crash

**Screenshots**
<img width="675" alt="Screenshot 2023-07-27 at 9 55 24 AM" src="https://github.com/DopplerHQ/cli/assets/9389424/1eb12a1b-f422-4f07-9a5b-01f3fe34463b">

**Desktop:**
 - OS: macOS
 - Version: Ventura 13.4.1. (c)

**CLI Version:**
Version: v3.65.1

**Additional context**
N/A

**Comment by Piccirello** [comment]
Fixed in #426
