### ISSUE TITLE
dopplerhq/cli-action@v2 throws spawnSync /bin/sh ETIMEDOUT error

### ISSUE THREAD

**Issue by JameelJiwani** [DopplerHQ/cli#439]
**Describe the bug**
When using the `dopplerhq/cli-action@v2` action, it throws an error: `Error: spawnSync /bin/sh ETIMEDOUT error`

**To Reproduce**

1. Create an action with `dopplerhq/cli-action@v2`
2. Trigger it to execute
3. Action should fail with `Error: spawnSync /bin/sh ETIMEDOUT error`

**Expected behavior**
Download the CLI successfully and move onto other actions

**Screenshots**
<img width="894" alt="Screenshot 2023-10-30 at 16 27 14" src="https://github.com/DopplerHQ/cli/assets/9706770/207e87d0-840c-4c13-b903-b310399c97a8">

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version:   22.04.3 (LTS)

**CLI Version:**
Version: Latest

**Additional context**
Looks like https://cli.doppler.com/install.sh is still working but other URLs are down

**Comment by watsonian** [comment]
@JameelJiwani This was related to a brief outage we had that caused cli.doppler.com to be intermittently available. It should be working fine now!
