### ISSUE TITLE
'doppler flags disable' Command Not Disabling. [BUG]

### ISSUE THREAD

**Issue by Terry-BrooksJr** [DopplerHQ/cli#452]
**Describe the bug**
I am using the doppler CLI provided via container.dev [feature](https://github.com/itsmechlark/features/tree/b596067481677d33c56380fd17b82ad23b682fd6/src/doppler).   Disabled the `env-warning` flag, and the output panel in VSCODE is still overrun with the message. I have enabled, autocompletion and hoover enrichment. 

 
**To Reproduce**
Steps to reproduce the behavior. Please include output from running the command with `--debug`.

1. Open Terminal with Doppler CLI 
2. Execute `doppler flags disable env-warning`
3. See confirmation of the updated settings that that setting has been updated
4. Hoover over  `os.getenv` or `process.env` code 
5. Observe the output panel still produces the warning message. 

**Expected behavior**
As a User Who Has explicitly disabled a flag's messaging, I should not see related messaging in the Output panel. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Sonoma 
 - Version 14.3.1 (23D60)

**CLI Version:**
Version 2.1.3 - Per Containers.dev 

**Additional context**
Personal opinion but I think the messaging needs to be more robust to include how to disable that flag, as well, or make it somehow above the fold when configuring or setting up the vs-code integration. Something like `Using DOPPLER_CONFIG_DIR from the environment. To disable this warning, use \'doppler flag disable env-warning\'. To set configs from stdin. Use --no-read-env `.

**Comment by watsonian** [comment]
@Terry-BrooksJr I'm able to reproduce this behavior with a configuration variable set in the shell that VSCode was launched from (e.g., `DOPPLER_ENABLE_VERSION_CHECK=false code .`) when the flag is enabled. When hovering over a secret, the terminal gets spammed like this:

![CleanShot 2024-03-18 at 10 09 16](https://github.com/DopplerHQ/cli/assets/244/4a7a6c11-3c95-4525-8298-82c131962f15)

However, when I disable the flag, that stops occurring on my end.

The `doppler flags` command sets a global value in your `~/.doppler/.doppler.yaml` file, which is where the CLI reads that from. Is it possible the context that you're launching VSCode from won't have the same file that this was saved in initially? It looks like you're using development containers – is that flag being set inside the container? Even if VSCode is executing from outside the container, the CLI is running inside the container. If you ran `doppler flags disable env-warning` outside the container, opened up the project, and were using devcontainers – then everything inside the terminal will be executing inside the container, not on your local machine. It's very possible this is what's happening for you.

**Comment by Terry-BrooksJr** [comment]
This can be resolved. It was ultimately the version of Doppler within the dev container features
