### ISSUE TITLE
[BUG] winget install doppler is ambiguous

### ISSUE THREAD

**Issue by gedw99** [DopplerHQ/cli#469]
```sh

winget install doppler
Multiple packages found matching input criteria. Please refine the input.
Name           Id              Source
--------------------------------------
Doppler Effect 9P6PD9HNTX2R    msstore
doppler        Doppler.doppler winget
```

**Comment by watsonian** [comment]
@gedw99 Thanks for writing in! The correct method of installing is via `winget install doppler.doppler`, which is described [in our documentation](https://docs.doppler.com/docs/install-cli):

![](https://github.com/user-attachments/assets/4182497e-4ab0-4d73-a41e-d611351b50a5)

**Comment by watsonian** [comment]
@gedw99 Our what now?
